/**
 * parity-regression.test.ts
 *
 * Lock the current trade-simulation behavior before the Task 9 refactor.
 * Asserts that the new `simulatePosition` (pessimistic + flat-friction + signal_close)
 * produces byte-for-byte identical results to the independently-computed legacy
 * expectation captured in the golden fixture.
 *
 * The fixture's `expected[]` was generated by scripts/gen-golden-slice.ts using
 * a self-contained legacyExpected() that replicates backtest-confluence.ts
 * arithmetic INLINE — it does NOT call simulatePosition, so the test is non-circular.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { simulatePosition } from '@/lib/sim/simulator';
import { DefaultFillModel } from '@/lib/sim/fill-model';
import { FlatFrictionCostModel } from '@/lib/sim/cost-model';
import type { Candle } from '@/types/candle';
import type { SimPosition, SimTradeResult, SimConfig } from '@/lib/sim/types';

// ---------------------------------------------------------------------------
// Fixture
// ---------------------------------------------------------------------------
interface GoldenExpected {
  entryPrice: number;
  exitPrice: number;
  pnlPercent: number;
  exitReason: SimTradeResult['exitReason'];
}

interface GoldenFixture {
  candles: Candle[];
  positions: SimPosition[];
  expected: GoldenExpected[];
}

const fixture = JSON.parse(
  readFileSync('tests/sim/fixtures/golden-run20-slice.json', 'utf-8'),
) as GoldenFixture;

// ---------------------------------------------------------------------------
// Shared constants — must match gen-golden-slice.ts exactly
// ---------------------------------------------------------------------------
const FRICTION = 0.0007;
const MAXBARS = 100;

// ---------------------------------------------------------------------------
// Test
// ---------------------------------------------------------------------------
describe('parity-regression: simulatePosition reproduces legacy backtest-confluence trades', () => {
  const fillModel = new DefaultFillModel(
    new FlatFrictionCostModel(FRICTION),
    { allowHeuristic: false }, // forces pessimistic tier — matches backtest-confluence SL-first rule
  );

  const cfg: SimConfig = {
    entryTiming: 'signal_close', // use position.entryPrice as the raw reference (== legacy)
    maxBars: MAXBARS,
    barMs: 3_600_000,            // 1-hour bars
    exitMode: 'simple',          // no partial TP, no trailing, no breakeven
  };

  it('fixture contains ≥30 trades with a mix of exit reasons', () => {
    expect(fixture.positions.length).toBeGreaterThanOrEqual(30);

    const reasons = new Set(fixture.expected.map((e) => e.exitReason));
    // Must have at least stop_loss and take_profit — if only max_bars the golden
    // cannot distinguish SL-first ordering from any other exit model.
    expect(reasons.has('stop_loss')).toBe(true);
    expect(reasons.has('take_profit')).toBe(true);
  });

  it('matches every golden trade on entry price, exit price, pnl, and exit reason', () => {
    fixture.positions.forEach((pos, idx) => {
      // startIndex = entryIndex + 1 mirrors production:
      // backtest-confluence calls simulatePositionSimple(pos, candles, i + 1) with
      // pos.entryIndex = i, so SL/TP checking starts on the bar AFTER the signal close.
      const result = simulatePosition(pos, fixture.candles, pos.entryIndex + 1, {
        fillModel,
        config: cfg,
      });

      expect(result).not.toBeNull();
      if (!result) return; // narrowing for TS — unreachable after expect above

      const exp = fixture.expected[idx];
      if (!exp) throw new Error(`Missing expected[${idx}]`);

      // entryPrice: cost-adjusted fill price (precision: 6 decimal places)
      expect(result.entryPrice).toBeCloseTo(exp.entryPrice, 6);

      // exitPrice: cost-adjusted exit (precision: 6 decimal places)
      expect(result.exitPrice).toBeCloseTo(exp.exitPrice, 6);

      // pnlPercent: gross return as fraction (precision: 9 decimal places)
      expect(result.pnlPercent).toBeCloseTo(exp.pnlPercent, 9);

      // exitReason: exact string match — this is the primary behavioral invariant
      expect(result.exitReason).toBe(exp.exitReason);
    });
  });
});
